title: Monarch Counter
logo: /images/monarch_logo.jpg
description: Data, code and implementation details about using deep learning methods to automate the counting of Monarch butterflies in dense clusters
theme: jekyll-theme-minimal
